# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f01d996b0a2da3698576dc7529dc8df4b0ce50458b81ef72770049399093037a6faeeb4933a5a4dbe6b148edb22a748bc9fbab9a13358047924b43fdfd1dfe65

test:
  secret_key_base: b09197f1b8fd1480802e98fe69917c8fbb2c46ce7485f5ae3aa9ca17e81615238c53c103da7c9996324d3478f49d084509dfcfa7ff764fe99f905aa6a967c91a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
